#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=${REPO_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}

# Mainline diagnostic: keep the experiment to 01125 + 00256 until task-vector
# sensitivity and retention both pass. Do not include 00186 in this wrapper.
export EXP_NAME=${EXP_NAME:-srsa_axial_online_family_rawtask_adapter_01125_00256}
export SOURCE_CHECKPOINT=${SOURCE_CHECKPOINT:-${REPO_ROOT}/logs/isaaclab-srsa-assembly/1/srsa_axial_online_family_polish_01125_00256/20260619_0135_retention_polish_stage-2_asm-00256/models/latest.pt}
export TARGETS=${TARGETS:-00256}
export RESUME_COMPLETED_TARGETS=${RESUME_COMPLETED_TARGETS:-01125}

export CURRENT_RATIO=${CURRENT_RATIO:-0.50}
export ANCHOR_RATIO=${ANCHOR_RATIO:-0.50}
export HISTORY_RATIO=${HISTORY_RATIO:-0.0}
export MIN_CURRENT_EPISODES=${MIN_CURRENT_EPISODES:-5}

export STEPS_PER_TASK=${STEPS_PER_TASK:-100000}
export NUM_ENVS=${NUM_ENVS:-256}
export RETENTION_NUM_ENVS=${RETENTION_NUM_ENVS:-256}
export ACQUISITION_STOP_ENABLED=${ACQUISITION_STOP_ENABLED:-false}
export ACQUISITION_REQUIRE_SUCCESS=${ACQUISITION_REQUIRE_SUCCESS:-false}
export RETENTION_REQUIRE_GATE=${RETENTION_REQUIRE_GATE:-true}
export UPDATE_PROGRESS_LOG_EVERY=${UPDATE_PROGRESS_LOG_EVERY:-50}

export TASK_CONTEXT_ADAPTER_ENABLED=${TASK_CONTEXT_ADAPTER_ENABLED:-true}
export TASK_CONTEXT_ADAPTER_SOURCE=${TASK_CONTEXT_ADAPTER_SOURCE:-raw_task_vec}
export TASK_CONTEXT_ADAPTER_ALPHA=${TASK_CONTEXT_ADAPTER_ALPHA:-0.005}
export TASK_CONTEXT_ADAPTER_HIDDEN_DIM=${TASK_CONTEXT_ADAPTER_HIDDEN_DIM:-128}
export TASK_CONTEXT_ADAPTER_APPLY_ENCODER=${TASK_CONTEXT_ADAPTER_APPLY_ENCODER:-true}
export TASK_CONTEXT_ADAPTER_APPLY_DYNAMICS=${TASK_CONTEXT_ADAPTER_APPLY_DYNAMICS:-true}
export TASK_CONTEXT_ADAPTER_APPLY_POLICY=${TASK_CONTEXT_ADAPTER_APPLY_POLICY:-false}
export TASK_CONTEXT_ADAPTER_APPLY_REWARD=${TASK_CONTEXT_ADAPTER_APPLY_REWARD:-false}
export TASK_CONTEXT_ADAPTER_APPLY_Q=${TASK_CONTEXT_ADAPTER_APPLY_Q:-false}
export TASK_CONTEXT_ADAPTER_LR_SCALE=${TASK_CONTEXT_ADAPTER_LR_SCALE:-0.1}
export ONLINE_FAMILY_SAMPLE_BALANCE=${ONLINE_FAMILY_SAMPLE_BALANCE:-ratio}

exec "${SCRIPT_DIR}/run_01125_online_family_acquire_targets.sh"
